[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd backend && npx prisma generate && npm run build"
]

[start]
cmd = "cd backend && node dist/index.js"
