-- ============================================================
-- 005 — Audit log & signatures electroniques (21 CFR Part 11)
-- Immutable : pas de UPDATE ni DELETE policy
-- ============================================================

create table if not exists public.audit_log (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users(id),
  action      text not null,
  entity      text not null,
  entity_id   text,
  of_id       uuid references public.ordre_fabrication(id),
  old_data    jsonb,
  new_data    jsonb,
  ip          text,
  created_at  timestamptz default now()
);

create table if not exists public.electronic_signature (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id),
  of_id       uuid references public.ordre_fabrication(id),
  action      text not null,
  meaning     text not null,
  signed_at   timestamptz default now()
);

-- RLS — lecture seule pour authentifiés, insertion autorisée, jamais de modif
alter table public.audit_log             enable row level security;
alter table public.electronic_signature  enable row level security;

create policy "sel" on public.audit_log            for select to authenticated using (true);
create policy "ins" on public.audit_log            for insert to authenticated with check (true);
create policy "sel" on public.electronic_signature for select to authenticated using (true);
create policy "ins" on public.electronic_signature for insert to authenticated with check (true);
-- Pas de policy UPDATE/DELETE → immuabilité garantie par RLS
