export const PERMISSIONS_LIST = [
  { key: 'users:read', label: 'Consulter les utilisateurs' },
  { key: 'users:create', label: 'Créer des utilisateurs' },
  { key: 'users:update', label: 'Modifier des utilisateurs' },
  { key: 'users:delete', label: 'Désactiver des utilisateurs' },
  { key: 'roles:read', label: 'Consulter les rôles' },
  { key: 'roles:manage', label: 'Gérer les rôles et permissions' },
  { key: 'of:read', label: 'Consulter les ordres de fabrication' },
  { key: 'of:create', label: 'Créer un ordre de fabrication' },
  { key: 'of:update', label: 'Modifier un ordre de fabrication' },
  { key: 'of:delete', label: 'Supprimer un ordre de fabrication' },
  { key: 'of:verify', label: 'Vérifier un ordre de fabrication' },
  { key: 'of:validate', label: 'Valider / clôturer un ordre' },
  { key: 'of:sign', label: 'Signer électroniquement' },
  { key: 'of:import', label: 'Importer depuis Excel' },
  { key: 'of:export', label: 'Exporter (Excel)' },
  { key: 'audit:read', label: "Consulter la piste d'audit" },
  { key: 'dashboard:read', label: 'Accéder au tableau de bord' },
];
